### ISSUE TITLE
Create a landing page for election resources hub

### ISSUE THREAD

**Issue by allanlasser** [MuckRock/squarelet#115]
As a placeholder before the launch of the resource catalog, the Election Resource Hub page should provide a description of the product and a form for email submissions.

Emails submitted through the form will be notified about the launch of the hub and the addition of resources to the catalog.

After launch, this landing page can be repurposed into a page for organizations to enroll in the Knight ERH program.

**Comment by amandabee** [comment]
Amanda is setting up a Mailchimp list -- emails submitted through the form will be added to that. 

Ideally we'll also give users some indication of whether they are in a verified newsroom or need to take additional steps to get verified if they want to be able to use the form. Currently this takes the form of organizational affiliation:

Are you a member of a Squarelet Org that is, in turn, a member of a membership org that vets newsrooms. [Full list](https://docs.google.com/document/d/1fQ3c3B5KFA_z2ZLel2qOSQn4ZYMvNsWhXwZf_KCydO8/edit)

**Comment by mitchelljkotler** [comment]
If they are logged in to squarelet I can display if they are in an org we currently have confirmed to be in one of the approved JSOs.  If they are not logged in we can prompt them to log in.

**Comment by amandabee** [comment]
````
<div id="mc_embed_shell">
      <link href="//cdn-images.mailchimp.com/embedcode/classic-061523.css" rel="stylesheet" type="text/css">
  <style type="text/css">
        #mc_embed_signup{background:#fff; false;clear:left; font:14px Helvetica,Arial,sans-serif; width: px;}
        /* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
           We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
    <form action="https://muckrock.us2.list-manage.com/subscribe/post?u=74862d74361490eca930f4384&amp;id=64f4342878&amp;f_id=00ebc0e1f0" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank">
        <div id="mc_embed_signup_scroll"><h2>Get updates from the Knight Election Resource Hub</h2>
            <div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
            <div class="mc-field-group"><label for="mce-EMAIL">Email Address <span class="asterisk">*</span></label><input type="email" name="EMAIL" class="required email" id="mce-EMAIL" required="" value=""></div><div class="mc-field-group"><label for="mce-FNAME">First Name </label><input type="text" name="FNAME" class=" text" id="mce-FNAME" value=""></div><div class="mc-field-group"><label for="mce-LNAME">Last Name </label><input type="text" name="LNAME" class=" text" id="mce-LNAME" value=""></div>
        <div id="mce-responses" class="clear">
            <div class="response" id="mce-error-response" style="display: none;"></div>
            <div class="response" id="mce-success-response" style="display: none;"></div>
        </div><div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_74862d74361490eca930f4384_64f4342878" tabindex="-1" value=""></div><div class="clear"><input type="submit" name="subscribe" id="mc-embedded-subscribe" class="button" value="Subscribe"></div>
    </div>
</form>
</div>
<script type="text/javascript" src="//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js"></script><script type="text/javascript">(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[3]='ADDRESS';ftypes[3]='address';fnames[4]='PHONE';ftypes[4]='phone';fnames[5]='MMERGE5';ftypes[5]='text';fnames[6]='MMERGE6';ftypes[6]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script></div>

```

**Comment by amandabee** [comment]
This is the basic text we can use at launch: 

Local newsrooms that are doing innovative work informing and connecting with communities often don’t have access to the services that newsrooms in earlier times took for granted. Small newsrooms are often so busy with daily coverage they don’t even know about all the resources available to answer their community’s hardest questions. That’s why we created the Resource Hub, and why we’re picking up the check. It’s a collection of more than 100 selected products and services that will help you cover the election better than you thought possible.

The Hub will open later this month, and we’ll add services throughout the summer. Any U.S. news organization covering the 2024 elections can get access. 

Make sure your newsroom is qualified, by … and sign up for updates so we can be sure to alert you when the hub is updated.

**Comment by allanlasser** [comment]
Additional context from @amandabee for when to show newsletter signup vs. application: 

> Some newsrooms will already have access -- we've confirmed that they're a member of LION, so they don't need to apply. But we do want them to let us know they want updates.

So:

- If the user belongs to an organization that is verified/confirmed, show a newsletter signup form.
- If the user belongs to an organization that isn't verified/confirmed, we show a link/embed of an application form.
- If the user isn't part of an organization, prompt them to join or create one.
- If the user is anonymous, prompt them to sign in.

**Comment by amandabee** [comment]
We want everyone to be able to sign up for the newsletter, whether or not their hub access is complete. 

On June 5, 2024 6:30:42 AM PDT, Allan Lasser ***@***.***> wrote:
>Additional context from @amandabee for when to show newsletter signup vs. application: 
>
>> Some newsrooms will already have access -- we've confirmed that they're a member of LION, so they don't need to apply. But we do want them to let us know they want updates.
>
>So:
>
>- If the user belongs to an organization that is verified/confirmed, show a newsletter signup form.
>- If the user belongs to an organization that isn't verified/confirmed, we show a link/embed of an application form.
>- If the user isn't part of an organization, prompt them to join or create one.
>- If the user is anonymous, prompt them to sign in.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/MuckRock/squarelet/issues/115#issuecomment-2149936091
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by allanlasser** [comment]
Update: This project no longer requires a pre-launch landing page, but these pages will instead be used for unauthorized users to request access to the hub.
