### ISSUE TITLE
Create Election Hub Verification Form

### ISSUE THREAD

**Issue by amandabee** [MuckRock/squarelet#121]
Basic verification form.

**Comment by amandabee** [comment]
`https://airtable.com/app93Yt5cwdVWTnqn/pagGarPPmVmWpU6d5/form?prefill_MR+User+Email=amanda%40poopoo.lala&prefill_MR+User+Display+Name=Amanda+Hickman&prefill_MR+User+Account+URL=fillme&prefill_MR+Organization+Name=fillme&prefill_MR+Organization+Account+URL=fillme` @allanlasser this is the form.

**Comment by amandabee** [comment]
Prefill Fields would be: 
* MR User Display Name: Amanda Hickman
* MR Account URL: https://accounts.muckrock.com/users/amandabee/
* MR User Email: {the primary email address associated with my account)
* MR Organization Name: MuckRock Staff
* MR Organization Account URL: https://accounts.muckrock.com/organizations/muckrock/
We want all of that so that Essential can work quickly.

**Comment by amandabee** [comment]
This is complete and we can implement links to it.

**Comment by allanlasser** [comment]
I have the URL to the form connected with user details, but it looks like some fields are filling unexpectedly. Maybe they're mixed up?

For example, here's the results for:

`https://airtable.com/app93Yt5cwdVWTnqn/pagGarPPmVmWpU6d5/form?prefill_MR+User+Email=allan@lasser.design&prefill_MR+User+Name=Allan%20Lasser&prefill_MR+User+Account+URL=/users/allan/&prefill_MR+Organization+Name=Test%20Org&prefill_MR+Organization+Account+URL=/organizations/test-org/`

<img width="1609" alt="Screenshot 2024-06-10 at 4 50 21 PM" src="https://github.com/MuckRock/squarelet/assets/6089482/3639f19d-b296-4b30-9321-7781de968635">
<img width="1609" alt="Screenshot 2024-06-10 at 4 50 52 PM" src="https://github.com/MuckRock/squarelet/assets/6089482/dc6188d5-96ee-4454-852e-c2a82d8b19de">

**Comment by amandabee** [comment]
If you do a fully qualified URL (eg.  "https://accounts.muckrockcom/organizations/test-org") does that fill for you? 

`prefill_MR+Organization+Account+URL=/organizations/test-org/`

**Comment by amandabee** [comment]
Apparently, we can't use a "prefill" to fill a locked field. So those are editable and should be working. The org name and user name were swapped. Those are fixed now.
