### ISSUE TITLE
Generate weekly reports

### ISSUE THREAD

**Issue by allanlasser** [MuckRock/squarelet#163]
Send to just amanda@muckrock.com to start off.

Needs stats to report. Stats can come from ERH Airtable or Plausible.

**Comment by amandabee** [comment]
https://docs.google.com/document/d/1pWwk_cjG2FP74MUfyapRsVGsv9XI-Ob_EWUCykfuK9M/edit captures what we're tracking.

Currently, I'm copying the last 7 days of visitor data from Plausible to a spreadsheet once a week.
