### ISSUE TITLE
Can we search for similar names when someone creates a new organization?

### ISSUE THREAD

**Issue by amandabee** [MuckRock/squarelet#165]
Someone just created an account for KUOW (https://accounts.muckrock.com/organizations/kuow-public-radio/) which surprised me because I would have expected them to be longtime users. So I looked, and ... they are: 

https://accounts.muckrock.com/organizations/kuowpublicradio/ 

We have a low key problem with duplicate organizations being created by new users who didn't think to search first. (See: SCPR, ProPublica) it would be really nice if we could find a way to say "Hey, you probably already have an account" when someone tries to create an organization that has a lot of semantic overlap with any existing organization.

**Comment by amandabee** [comment]
I think we probably want to give them a few choices like:
* Nope, my organization is not one of those.
* Yes, my organization is shown in this list but there's a problem.

**Comment by allanlasser** [comment]
<img width="1130" alt="Screenshot 2024-07-11 at 11 30 15 AM" src="https://github.com/MuckRock/squarelet/assets/6089482/6c24e207-bf7f-4eb2-9ea8-6dace5f3c532">

The create organization form is very simple now, I think there's plenty of space to improve it by running a search before enabling the "Create" button.

**Comment by amandabee** [comment]
What is on staging now is fine. Though one way it could work is to mimic the search box and populate with likely matches: 
![image](https://github.com/user-attachments/assets/0e6e9380-83e1-4937-a938-3b17b2811689)


Demo text on staging now reads: 
> We found some organizations with a similar name. If your organization already exists, please join the existing one instead of creating a new one.

> My organizations is not one of the ones listed above:

Instead, it should read: 
> It looks like one or more organizations with similar names are already up and running on MuckRock:

* Similar Org One (Verified)
* Similar Org Two

> If the organization you're trying to create is already set up on MuckRock, please look for the "Request to Join" option on the organization's profile page. Please _contact support_ if you the admins listed have left the organization. 
>  My organization is not shown.

Editable name box

> Create Organization (so the button stays constant).
