### ISSUE TITLE
If I add a parent, shouldn't the child appear as a member?

### ISSUE THREAD

**Issue by amandabee** [MuckRock/squarelet#166]
See:

https://accounts.muckrock.com/organizations/cbs-chicago/ has "CBS News" as a parent. but I don't see any members under https://accounts.muckrock.com/organizations/cbsnews/ 

I think Miranda was going to file a related ticket about adding multiple parents, so we can tag newsrooms as members of multiple networks/orgs (eg. PMJA + INN + LION)

**Comment by amandabee** [comment]
It makes it hard to troubleshoot stuff like this: 

[RJI](
https://accounts.muckrock.com/organizations/reynolds-journalism-institute/) asked for access to the hub. I could swear that I'd taken care of that weeks ago so I looked. I see "Election Resource Hub" under "Members"  which is backwards. They should be a member OF "Election Resource Hub" but if I look at the Election Resource Hub org, I don't see RJI as a parent.

**Comment by mitchelljkotler** [comment]
Parent and Member are not related, they are two separate concepts.

Member is made for when one organization is a member of another organization, such as INN or LION.  You can be a member of multiple organizations.

Parent is for when an organization is owned by a parent company.  Examples would be the various MuckRock organizations being owned by the top level MuckRock organization, or Gannet subsidiary's having Gannet as their parent.  An organization should never have more than one parent.

Right now you can inherit hub access from either a parent or from an organization you are a member of.

If we want to show the reverse relationships on the backend, we could do that.

If we want to change the terminology to make this less confusing, we could do that as well.

If we want to change how these relationships actually work, that could also be an option.

**Comment by mitchelljkotler** [comment]
* Add reverse relationship, so you can add membership from the organization page
