### ISSUE TITLE
Individuals can't have members

### ISSUE THREAD

**Issue by amandabee** [MuckRock/squarelet#180]
The "Memberships" lookup leads with a lot of "Individual" orgs. But you shouldn't be able to be a "member" of an individual org at all. 

![image](https://github.com/user-attachments/assets/0c8d995c-0e12-4019-b25e-f54a4bd1c4e4)

**Comment by amandabee** [comment]
![image](https://github.com/user-attachments/assets/62a074fe-6487-4f39-892b-7441d431affd)

I had to scroll past a TON to ID these guys as members of INN. :sweat:

**Comment by mitchelljkotler** [comment]
This is surprisingly more difficult than it is worth - going to close as won't fix - if it is really pressing we can re-visit
