### ISSUE TITLE
Revise Welcome Message

### ISSUE THREAD

**Issue by amandabee** [MuckRock/squarelet#181]
When someone creates a new MuckRock account, we send a welcome message. This should be revised: 

https://www.notion.so/muckrock/Existing-Welcome-Message-2f06c6ee4b3546c79b0dce87389d1993 has the original. We should revise it to:

> Thank you for creating an account on MuckRock. 
> 
> Your username is {USERNAME}. You will need to [verify your email address](link) before you can start using our tools. You can also verify your email from your [account email settings](-). 
> 
> **Have a technical support or customer service issue? [Email us](mailto:info@muckrock.com).** 
> 
> Welcome to the MuckRock community. We're excited to see what you do with the tools we've built. 
> 
> Sincerely, 
> The MuckRock Team

 This email was sent to ... etc can stay the same.

**Comment by duckduckgrayduck** [comment]
email_confirmation_signup_message.html

Is where this lives
