### ISSUE TITLE
Set active organization or something?

### ISSUE THREAD

**Issue by amandabee** [MuckRock/squarelet#187]
Per <https://github.com/MuckRock/documentcloud-frontend/issues/610>, we need to figure out a solution to this: 

We are oulling the user's Individual organization. For example: Gaetan Gras wants is requesting verification for IHECS. They created an organization (https://accounts.muckrock.com/organizations/ihecs/) but what I'm seeing in their [verification request](https://muckrock.zendesk.com/agent/tickets/131632) is:

    https://accounts.muckrock.com/organizations/gaetangras

This is consistent -- I"m always getting their "individual" org.

**Comment by duckduckgrayduck** [comment]
This is an issue we already have captured in https://github.com/MuckRock/documentcloud/issues/239
Closing this as it is a duplicate. We are working on this week
