### ISSUE TITLE
How to customize emails

### ISSUE THREAD

**Issue by jacqui** [MuckRock/squarelet#50]
Hi, I was trying to sort out a reasonable way to customize emails for PressPass users, and I'm wondering if you have any ideas.

Specifically:

* how do we distinguish emails originating from PressPass vs from MuckRock?
  * can we rely on `user.source` being `PressPass` (and available) to switch things like template & from address?
  * is this reasonable to do in all the places emails get sent from?
* is this better addressed as a configuration setting?
  * in the past I've done things like creating organization-specific templates in directories named `$organization.slug` then rely on that convention to render the right version

I'd be happy to brainstorm this some more, but I thought I'd reach out and ask if you had a plan or suggestion that will be manageable for all. Thanks!

**Comment by mitchelljkotler** [comment]
Can we distinguish based on what triggers the email?  IE if something in PressPass code triggers the email, use PressPass template, etc.  I can imagine at some point having users who use both so this would be needed to handle that case.  It is also possible I am misinterpreting the question, so if you had some more concrete examples that might help.

**Comment by TylerFisher** [comment]
Given that `send_mail` is [called in signals and model methods](https://github.com/MuckRock/squarelet/search?q=send_mail&unscoped_q=send_mail), it might be hard to distinguish in that way sometimes. I hear your point that we could have users of both systems though.

**Comment by jacqui** [comment]
Ah, @mitchelljkotler that's a good point about people being users of several systems. Let me have a look through the code again and think some more about it.
