### ISSUE TITLE
Password reset emails never received

### ISSUE THREAD

**Issue by adriensalz** [MuckRock/squarelet#94]
Users have written into Zendesk saying they never received password reset emails from us. This includes users affiliated with newsrooms, including ProPublica, an ABC affiliate station, and Chicago Sun Times email domains, as well as Hotmail and Yahoo personal emails.

https://muckrock.zendesk.com/agent/tickets/121645
https://muckrock.zendesk.com/agent/tickets/118604
https://muckrock.zendesk.com/agent/tickets/119939
https://muckrock.zendesk.com/agent/tickets/119123
https://muckrock.zendesk.com/agent/tickets/119034
https://muckrock.zendesk.com/agent/tickets/117082

This seems to have been ongoing since at least August 28.

I've been able to confirm in our diagnostics inbox that these emails are being generated and have send timestamps, but none of the users above were able to find the emails in their Spam folder or their main inbox.

![image](https://github.com/MuckRock/squarelet/assets/145583396/09465c13-407a-4214-88cb-b3933d7bc570)

I sent a password reset to myself and received it within a minute using both my MuckRock email and my personal Gmail account.

![image](https://github.com/MuckRock/squarelet/assets/145583396/0b4dc3ac-0ab9-4632-ac5b-ab882e59443c)
![image](https://github.com/MuckRock/squarelet/assets/145583396/6384d802-9e0b-4568-a541-f844b6b3f17c)

I've been able to get these users their password reset emails in the past by manually forwarding it to them from adrien@muckrock.com, but this is time-consuming and users have complained about not receiving the email sooner. I'm not sure how frequently this is occurring and I haven't been able to reproduce this bug personally.

**Comment by mitchelljkotler** [comment]
They rotated our IP, this should prevent our emails from being black holed

> After reviewing the currently assigned IP, it appears that a problematic sender led to the IP's listing on a reputable blocklist. While we work to delist this IP, we have reassigned your sending to a new IP.
